version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cashflow-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - cashflow-network

  postgres:
    image: postgres:16-alpine
    container_name: cashflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-cashflow}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cashflow-network

  redis:
    image: redis:alpine
    container_name: cashflow-redis-transactions
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - cashflow-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashflow-api
    depends_on:
      - postgres
      - rabbitmq
      - redis
    ports:
      - "5000:80"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APP_TYPE=api
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-cashflow}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME:-transactions}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - REDIS_CONNECTION=redis:6379
    networks:
      - cashflow-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashflow-worker
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - redis
    environment:
      - DOTNET_ENVIRONMENT=Development
      - APP_TYPE=worker
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-cashflow}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME:-transactions}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - REDIS_CONNECTION=redis:6379
    networks:
      - cashflow-network


networks:
  cashflow-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 